/**
 * EVERY SAFETY LIMIT IN THE AUTOMATION FEATURE, AND THE ONLY PLACE ANY
 * OF THEM IS WRITTEN DOWN.
 *
 * No numeric limit belongs anywhere else — not in a Zod schema, not in a
 * validation function, not in the execution engine, not in a SQL
 * function, not in a UI string. Every one of those reads from here by
 * name. The SQL functions in 20260921120000_automations.sql take their
 * limits as PARAMETERS for exactly this reason: the database is
 * deliberately incapable of holding an opinion of its own about any
 * number in this file.
 *
 * WHY THIS MATTERS MORE HERE THAN ELSEWHERE. This is the first feature
 * in the app that acts on its own, unattended, on a schedule. A limit
 * that exists in two places is a limit that will eventually disagree
 * with itself, and the moment it does, the tighter copy is doing nothing
 * and nobody knows which copy that is. There is no user watching to
 * notice.
 *
 * The same values apply to every automation regardless of how it was
 * authored. There is no AI variant of any number below, and no code path
 * anywhere reads `origin` to pick a different one.
 */

/**
 * How many actions may execute in total across every automation
 * descended from a single originating event.
 *
 * Bounds the FAN-OUT case: ten automations all listening for
 * lead.created, each creating a task, is ten writes from one lead. It is
 * counted per root event rather than per automation so that adding an
 * eleventh automation cannot quietly raise the ceiling.
 */
export const MAX_ACTIONS_PER_EVENT = 10;

/**
 * How many generations of event an action may set off.
 *
 * Bounds the CHAIN case: an action producing an event that triggers
 * another automation, whose action produces another event. Depth 0 is an
 * event the application itself raised (a lead was created); depth 1 is
 * an event an automation caused.
 *
 * UNREACHABLE IN v1 AND KEPT ANYWAY — see the migration's design note 6.
 * The only action today is task.create, and creating a task raises no
 * event, so nothing can currently exceed depth 0.
 */
export const MAX_WORKFLOW_DEPTH = 3;

/**
 * How many times one event may be attempted before it is retired to
 * `dead` instead of retried forever.
 *
 * Counts CLAIMS, not failures — an attempt is recorded when a worker
 * takes the event, so a worker that dies silently mid-run still consumes
 * one. That is deliberate: an event that kills its worker three times is
 * exactly as unfit for a fourth attempt as one that failed cleanly.
 */
export const MAX_RETRIES_PER_EVENT = 3;

/**
 * How long a claimed event may stay in `processing` before another
 * worker is allowed to reclaim it.
 *
 * Must comfortably exceed the worst-case runtime of one batch, or a slow
 * run gets reclaimed underneath itself and processed twice. Duplicate
 * work is still safe — the idempotency key and the unique run constraint
 * both hold — but it is wasted, and it inflates the attempt count of an
 * event that was never actually failing.
 */
export const PROCESSING_TIMEOUT_SECONDS = 300;

/** Nodes in one workflow, trigger and actions included. */
export const MAX_NODES_PER_WORKFLOW = 25;

/** Edges in one workflow. */
export const MAX_EDGES_PER_WORKFLOW = 40;

/**
 * Events claimed per cron invocation. Bounds how long one run can take,
 * which is what keeps it inside a serverless function's own time limit.
 */
export const EVENT_BATCH_SIZE = 25;

/**
 * How far ahead of the triggering event an automation may schedule a
 * task's due date. Bounds a misconfigured or AI-suggested offset from
 * producing a task due in the year 3000.
 */
export const MAX_DUE_DATE_OFFSET_DAYS = 365;

/** Characters in a generated task subject. */
export const MAX_SUBJECT_LENGTH = 200;

/** Characters in a generated task description. */
export const MAX_DESCRIPTION_LENGTH = 2000;

/** People in one round-robin rotation. */
export const MAX_ROUND_ROBIN_POOL = 25;

/** Characters of plain-English description accepted by the AI builder. */
export const MAX_AI_PROMPT_LENGTH = 1000;

/** Sources one "Lead source is" condition may name. */
export const MAX_TRIGGER_SOURCES = 50;

/** Characters in an automation's name and description. */
export const MAX_AUTOMATION_NAME_LENGTH = 120;
export const MAX_AUTOMATION_DESCRIPTION_LENGTH = 500;

/** Characters in a node or edge id. Ids are generated by the builder, so
 *  this only ever bounds something that arrived from outside. */
export const MAX_NODE_ID_LENGTH = 100;

/** Absolute bound on a canvas coordinate. Finite AND bounded: a
 *  position arriving as 1e308 would be stored happily and then break the
 *  builder for whoever opened it next. */
export const MAX_CANVAS_COORDINATE = 100_000;

// ---------------------------------------------------------------------
// AI request budget
// ---------------------------------------------------------------------
//
// Not workflow safeguards, but they ARE numeric limits, and the rule
// this file exists to enforce does not have an exception for limits that
// feel like tuning. They live here so there is exactly one place to look.

/** Smaller than the meeting-notes budget: a workflow is a handful of
 *  small objects, where a meeting extraction can be pages of action
 *  items. Still generous enough for a reasoning model's hidden tokens,
 *  which count against the budget before any content is emitted. */
export const AI_MAX_TOKENS = 1800;

/** Per attempt, not per request. */
export const AI_REQUEST_TIMEOUT_MS = 45_000;

/** Clarifying questions the AI builder may come back with at once. More
 *  than a handful stops being a conversation and starts being a form. */
export const MAX_AI_QUESTIONS = 5;

/** Characters in the AI's own plain-English summary of what it built,
 *  and in its explanation of why it could not. */
export const MAX_AI_SUMMARY_LENGTH = 600;

/**
 * How deeply a condition group may nest (a group inside a group inside
 * a group...). Bounds both the builder UI's recursion and the server's
 * validation walk — an unbounded tree is a stack-depth risk in both.
 */
export const MAX_CONDITION_GROUP_DEPTH = 3;

/** Rules or nested groups directly inside one condition group. Bounds
 *  how wide a single AND/OR row can get before it should be restructured
 *  into nested groups instead. */
export const MAX_CONDITION_GROUP_RULES = 10;

/** Characters in the Update Lead action's "next step" text. */
export const MAX_NEXT_STEP_LENGTH = 200;

/** Characters in a condition rule's own operator string (an internal
 *  key like "greater_than_or_equal", never user-typed). */
export const MAX_CONDITION_OPERATOR_LENGTH = 30;

/** Characters in one condition rule's comparison value (or one entry of
 *  an is_any_of list). */
export const MAX_CONDITION_VALUE_LENGTH = 500;

/** Values in one is_any_of list. */
export const MAX_CONDITION_VALUE_LIST_LENGTH = 50;

/** Characters in the Update Lead action's deal-value text input (kept as
 *  text, not a number field — see the registry's own note on why —
 *  so this bounds the string length, generous enough for any real
 *  currency amount typed with no separators). */
export const MAX_DEAL_VALUE_TEXT_LENGTH = 20;

/** Named outcomes one Decision node may define, default path excluded —
 *  more than this stops being a decision and starts being a table best
 *  split across a couple of decisions. */
export const MAX_DECISION_OUTCOMES = 8;

/** Characters in one Decision outcome's name. */
export const MAX_OUTCOME_NAME_LENGTH = 60;

/** Characters in an edge's `branch` value. Generalised (see
 *  types/automation.ts) from the original fixed "true"/"false" pair to
 *  any string so a Decision's own outcome ids can be edge branches too —
 *  this is what bounds that string now that it is no longer a two-value
 *  enum. */
export const MAX_BRANCH_ID_LENGTH = 60;

/** Assignments one Assignment node may hold in its list. */
export const MAX_ASSIGNMENTS_PER_NODE = 10;

/**
 * The hard cap on how many records ONE "Get Records" call can return —
 * enforced twice, not once: as the SQL scan LIMIT in
 * get_automation_records (so the query itself never reads more rows
 * than this off disk) and again as the max value the config panel's
 * own "How many" field accepts. Get Records reads the object's most
 * RECENT rows up to this many, then filters them in memory using the
 * SAME evaluateFieldGroup engine a Decision/Condition already uses — it
 * does not scan the whole table looking for matches, so an older
 * matching row beyond this window is a stated limitation (see the
 * registry entry's own `limitations`), not a silent gap.
 */
export const MAX_RECORDS_PER_QUERY = 200;

/**
 * The hard cap on how many items one Loop node will iterate, regardless
 * of how large the collection variable it was handed actually is.
 *
 * Composes with MAX_ACTIONS_PER_EVENT rather than duplicating it: this
 * number bounds the LOOP's own ceiling; MAX_ACTIONS_PER_EVENT
 * separately bounds the total actions across the whole event (this
 * loop's iterations included), checked the identical way every other
 * action already is. A loop cannot use one to bypass the other — see
 * the Loop executor's own note in registry/executors.ts.
 */
export const MAX_LOOP_ITERATIONS = 50;

/** Characters in a workflow variable's name. Kept short — a variable
 *  name is an internal token substituted verbatim into `{{var.name}}`,

*  not free text. */
export const MAX_VARIABLE_NAME_LENGTH = 40;

/** Characters in one Assignment's static value input. */
export const MAX_VARIABLE_VALUE_LENGTH = 500;

/** Characters in a Contact's name via Update/Create Contact — matches
 *  the human-facing Create Contact form's own NAME_MAX_LENGTH. */
export const MAX_CONTACT_NAME_LENGTH = 200;

/** Characters in a Contact's company, title, email, or phone via
 *  Update/Create Contact — the human-facing form leaves these
 *  unbounded (a plain optional text input); an automation-facing one
 *  does not get to, per this file's own rule that no free-text field
 *  reachable from a workflow definition is ever unbounded. */
export const MAX_CONTACT_TEXT_FIELD_LENGTH = 200;

/** Characters in a node-reference field's target node id — the same
 *  kind of bound as MAX_NODE_ID_LENGTH, reused for exactly the same
 *  reason: an internal identifier string, not user-typed text. */
export const MAX_NODE_REFERENCE_LENGTH = MAX_NODE_ID_LENGTH;

/**
 * Minimum length of the automation worker token.
 *
 * MIRRORED IN SQL, and that is a deliberate exception to this file's own
 * rule — `automation_worker_config_token_length` in
 * 20260921120000_automations.sql states the same bound, because a CHECK
 * constraint cannot import a TypeScript constant and a bearer secret
 * should not be storable at a weaker length just because the
 * application forgot to check. The two are allowed to agree; if they
 * ever disagree, the database is the stricter one and wins.
 */
export const MIN_WORKER_TOKEN_LENGTH = 32;

/**
 * The subset of the above that is safe to render in the product, with
 * the plain-English meaning each number carries.
 *
 * A SUBSET BY CONSTRUCTION, NOT BY HABIT. Publishing the whole file
 * would tell anyone reading the page exactly how many attempts it takes
 * to exhaust an event's retry budget and exactly how long a claim is
 * held — operational detail that helps nobody using the builder and
 * tells a probe where the edges are. What is here is what an admin needs
 * in order to build a workflow that will not be rejected.
 */
export const PUBLIC_SAFEGUARDS: ReadonlyArray<{ label: string; value: string; detail: string }> = [
  {
    label: "Nodes per workflow",
    value: String(MAX_NODES_PER_WORKFLOW),
    detail: "Counting the trigger, every condition and every action on the canvas.",
  },
  {
    label: "Connections per workflow",
    value: String(MAX_EDGES_PER_WORKFLOW),
    detail: "Lines joining one node to the next.",
  },
  {
    label: "Actions per triggering event",
    value: String(MAX_ACTIONS_PER_EVENT),
    detail:
      "Shared across every automation that responds to the same event, so adding another automation does not raise the ceiling.",
  },
  {
    label: "Round-robin list size",
    value: String(MAX_ROUND_ROBIN_POOL),
    detail: "People one rotation can hand work to.",
  },
  {
    label: "Furthest due date",
    value: `${MAX_DUE_DATE_OFFSET_DAYS} days`,
    detail: "How far ahead of the trigger a task may be scheduled.",
  },
];
